Реализовал проект с учётом ТЗ 13
Chernosmaga/java-shareit pull request #1
Opened 2023-09-15 15:00 UTC by Chernosmaga

2023-09-16 16:53 UTC, PolnySkvorets requested changes
Привет! Замечаний почти нет, только по оформлению имен методов - посмотри замечание

2023-09-16 16:53 UTC, PolnySkvorets commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +    public User createUser(User user) {
Если ты работаешь с сущностью пользователя не нужно в имени метода это указывать, достаточно create(User user) и так везде

2023-09-16 17:07 UTC, Chernosmaga commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +    public User createUser(User user) {
Понял, исправлю

2023-09-17 15:32 UTC, PolnySkvorets commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
>  public class BookingController {
пустой контроллер, если не нужен, то лучше удалить

2023-09-17 15:32 UTC, PolnySkvorets commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
>  public class BookingDto {
Не используется

2023-09-17 15:33 UTC, PolnySkvorets requested changes
Привет! Пропущены неиспользуемые классы, думаю, что можно почистить код от них

2023-09-18 16:19 UTC, PolnySkvorets approved these changes
всё отлично, принято!

2023-09-18 16:22 UTC, merged