feat: реализовал проект с учетом ТЗ 16
Chernosmaga/java-shareit pull request #4
Opened 2023-11-21 14:12 UTC by Chernosmaga

2023-11-22 14:41 UTC, PolnySkvorets commented on server/src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> -                                               @RequestParam(required = false, defaultValue = "10") Integer size) {
А почему без валидации?

2023-11-22 14:41 UTC, PolnySkvorets commented on server/src/main/resources/application.properties
> +#spring.datasource.password=password
Комментарии не оставляй, или удали или рскомментируй

2023-11-22 14:43 UTC, PolnySkvorets requested changes
Привет! Замечаний почти нет, там видел опечатка в имени пакета shateit - поправь, и мелкие замечания, по валидации я не понял, зачем это нужно было убрать.

2023-11-22 15:00 UTC, Chernosmaga commented on server/src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> -                                               @RequestParam(required = false, defaultValue = "10") Integer size) {
В ТЗ указано, что валидацию нужно в контроллер модуля `gateway` вынести

2023-11-23 11:39 UTC, PolnySkvorets approved these changes
замечания исправлены, хорошая работа

2023-11-24 16:31 UTC, merged